Implementing the small FR DISTMYSQL-182 as also suggested by customer…
percona/orchestrator pull request #5
Opened 2022-06-29 05:24 UTC by Tusamarco

… in the comments, just adding the <db>.Ping() to check if the instance is really available or not.
In my view this is more a bug fix than a FR. It makes no sense to have :
```
	db, err := db.OpenDiscovery(instanceKey.Hostname, instanceKey.Port)
	latency.Stop("instance")
	if err != nil {
		goto Cleanup
	}
```
Without checking the DB connectivity as well.

2022-07-04 10:00 UTC, kamil-holubicki requested changes

2022-07-25 13:12 UTC, Tusamarco commented on go/inst/instance_dao.go
> +	err = db.Ping()
Right @kamil-holubicki done, added a small err check on the DB object

2022-07-26 09:38 UTC, kamil-holubicki approved these changes
lgtm. 
Please correct formatting issues before merging.

2022-07-26 09:38 UTC, kamil-holubicki commented on go/inst/instance_dao.go
> +	}else{
wrong formatting

2022-07-26 09:38 UTC, kamil-holubicki commented on go/inst/instance_dao.go
> +	if err == nil {
Not a strong suggestion, but consider the following flow which at least for me seems to more straightforward and clean:
```	
        db, err := db.OpenDiscovery(instanceKey.Hostname, instanceKey.Port)
	if err != nil {
		latency.Stop("instance")
		goto Cleanup
	}

	err = db.Ping()
	latency.Stop("instance")
	if err != nil {
		goto Cleanup
	}
```

2022-07-26 12:47 UTC, merged